$(document).ready(function() {
  $('.updateUserName').click(function(){
    $('.unDisplay').slideToggle(200);
  })
  $('.updateName').click(function(){
    $('.displayNameUpdate').slideToggle(200);
  })
  $('.updatePhoneNumber').click(function(){
    $('.displayPhoneUpdate').slideToggle(200);
  })
  $('.updateBirthday').click(function(){
    $('.displayUpdateBirthday').slideToggle(200);
  })
  $('.updateAddress').click(function(){
    $('.displayAddressUpdate').slideToggle(200);
  })
  $('.updateEmail').click(function(){
    $('.displayEmailUpdate').slideToggle(200);
  })
  $('.updatePassword').click(function(){
    $('.displayPasswordUpdate').slideToggle(200);
  })
  $('.xmark').click(function(){
    $('.inputContainer').slideUp(200);
  })
  $('.okBtn').click(function(){
    $('.inputContainer').slideUp(200);
  })
  $('.fileInputLabel').click(function(){
    $('.labelDiv').css('display','none');
    $('.labelOk').css('display','block');
  })
  $('.okLabel').click(function(){
    $('.labelOk').css('display','none');
    $('.labelDiv').css('display','block');
  })
});